version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3333/api/
    networks:
      - gestion_sim_network
    restart: unless-stopped

networks:
  gestion_sim_network:
    driver: bridge