export const CLIENT_STATUSES = {
    ALL: 'TOUS',
    UP_TO_DATE: 'A JOUR',
    OVERDUE: "EN RETARD",
    SUSPENDED: 'DETTE',
    TERMINATED: 'RÉSILIÉ',
    NEEDS_TO_BE_ACTIVATED: 'A ACTIVER',
    NEEDS_TO_BE_DEACTIVATED: 'A DESACTIVER',
    NEEDS_TO_BE_REPLACED: 'A REMPLACER',
    NEEDS_TO_BE_ORDERED: 'A COMMANDER',
    TEMPORARILY_ASSIGNED: 'ATTRIBUÉ TEMPORAIREMENT',
    ACTIVE: 'ACTIF',
    INACTIVE: 'INACTIF',
    CANCELLED: 'ANNULÉ',
    UNATTRIBUTED: 'NON ATTRIBUÉ',
    REIMBURSED: 'REMBOURSÉ',
    REFUNDED: 'REMBOURSEMENT',
    DISPUTED: 'CONTESTÉ',
    CHARGEBACK: 'CHARGEBACK',
    FRAUDULENT: 'FRAUDULEUX',
  };
  
  export const TAB_TYPES = {
    LIST: 'UP_TO_DATE',
    TO_UNBLOCK: 'REIMBURSED',
    TO_BLOCK: 'OVERDUE',
    TO_ORDER: 'NEEDS_TO_BE_ORDERED',
    LATE: 'OVERDUE',
    TO_ACTIVATE: 'NEEDS_TO_BE_ACTIVATED'
  };

  export const PAYMENT_STATUS = {
        "UP_TO_DATE" : "UP_TO_DATE",
        "OVERDUE" : "OVERDUE",
        "PAST_DUE": "PAST_DUE",
        "DISCONNECTED": "DISCONNECTED",
        "UNATTRIBUTED" : "UNATTRIBUTED",
        "CANCELLED": "CANCELLED",
        "REIMBURSED" : "REIMBURSED",
        "REFUNDED" : "REFUNDED",
        "DISPUTED" : "DISPUTED",
        "CHARGEBACK" : "CHARGEBACK",
        "FRAUDULENT": "FRAUDULENT",
  }

  export const PHONE_STATUS = {
          "NEEDS_TO_BE_ACTIVATED": "NEEDS_TO_BE_ACTIVATED",
          "NEEDS_TO_BE_DEACTIVATED": "NEEDS_TO_BE_DEACTIVATED",
          "NEEDS_TO_BE_REPLACED": "NEEDS_TO_BE_REPLACED",
          "NEEDS_TO_BE_ORDERED": "NEEDS_TO_BE_ORDERED",
          "RESERVED_EXISTING_LINE": "RESERVED_EXISTING_LINE",
          "RESERVED_NEW_LINE": "RESERVED_NEW_LINE", 
          "TEMPORARILY_ASSIGNED": "TEMPORARILY_ASSIGNED",
          "NEEDS_NEW_ACCOUNT": "NEEDS_NEW_ACCOUNT",
          "ACTIVE": "ACTIVE",
          "INACTIVE": "INACTIVE",
          "SUSPENDED": "SUSPENDED",
  }
  
  export const ORDER_FILTERS = {
    NEW_CLIENT: 'NOUVEAU CLIENT',
    SIM_ORDER: 'COMMANDE CARTE SIM'
  };